### ISSUE TITLE
Infinite loop under conditions

### ISSUE THREAD

**Issue by netgfx** [namniak/canvas-text-wrapper#15]
Hey,

If entering more than 7 letters in a word a space and then another word the script goes into an infinite loop. here are my settings:

 var textStyle = "140px narziss-medium";
var textLineHeight = "139px";
var text = "QWE123QWE QWEQWE"

CanvasTextWrapper(canvas, text, {
            font: textStyle,
            lineHeight: textLineHeight,
            textAlign: "center",
            verticalAlign: "middle",
            paddingX: 40,
            paddingY: 40,
            lineBreak: "auto",
            strokeText: false,
            allowNewLine: true
        });

Any ideas?

**Comment by namniak** [comment]
Hi,

Interesting. I have no idea actually. 
Seems like some specific case. Not sure. I'll need to investigate when I have time.

**Comment by netgfx** [comment]
Thanks I appreciate it! Probably something in the condition of the do...while

**Comment by netgfx** [comment]
The problem is inside: ``` breakText(words) ```
for some reason the ```i``` gets increased to infinite.

However if use ```justifyLines``` that doesn't happen.

**Comment by namniak** [comment]
Hey, this should be fixed!
