### ISSUE TITLE
Wrong behavior of the "allowNewLine" option with two or more consecutive line breaks (\n\n)

### ISSUE THREAD

**Issue by yennare** [namniak/canvas-text-wrapper#16]
hi,
there's a problem when you try to put two or more than one line break, one after another, into a text.

a text like this:
`Vestibulum ante \n\n ipsum primis in faucibus orci luctus et \n\n ultrices posuere cubilia Curae;`

will result in something like this:

> Vestibulum ante 
> ipsum
> primis in faucibus orci luctus et 
> ultrices 
> posuere cubilia Curae;

while it should be like this:

> Vestibulum ante 
> 
> ipsum primis in faucibus orci luctus et 
> 
> ultrices posuere cubilia Curae;  

notice how, in the first example, we have a line break before and after the first word coming after the double \n.  

Just thought it would be nice to have the possibility to use more consecutive line breaks.

Hope this might help to fix the problem.

**Comment by namniak** [comment]
Hi. Thanks for your comment.

The original idea was to use this mostly for titles and not paragraphs etc. as it doesn't have much of formatting options anyway. If you want to have bigger gaps between lines then just use '\n' to break them where needed and set ```lineHeight```.  But obviously this won't help if you want to have different gaps between the lines. 

It'd be a nice feature for sure but probably won't happen soon as it'll require some serious refactor.

**Comment by yennare** [comment]
Hey thanks for the heads up.

The actual formatting system works just fine if you are the one that creates titles, but i'm building a Chrome extension (soon on Github) that fetch a text from a website and put it in a canvas and god only knows how that text comes out from html... :)  

Anyways, i used a regEx in my code to "clean" the text and make it work with your library, looking forward for this feature to be implemented.

**Comment by choiRyan** [comment]
Hey, I had the same issue (note: working only with node-canvas) and started with something similar to the above poster, but considered using a second delimiter placed where necessary in the incoming string. I could get text to show up like this:

`str = "mind the\n\n\ngap please\n\nAnd there's another one, and wait\n\n\n\na big one!"`
![text0](https://user-images.githubusercontent.com/5291713/28488047-3d6e6ba4-6e56-11e7-8cf0-afcb8ca7b8c5.png)

For instance, I used `\u200B` as the second delimiter (after seeing that `\u200A` was already being used :) and `\u200B` isn't caught by the splitting regex either). I replaced all `\n\n` in my input string with `\n\u200B\n` until there were no more consecutive `\n`:

```
// prepare input string str
while (str.indexOf('\n\n') > -1) {
    str = str.replace(/\n\n/g, '\n\u200B\n')
}
```

So `mind the\n\ngap please` becomes `mind the\n\u200B\ngap please`.

In `drawText()`, I replaced the line:

```
context.fillText(lines[i], textPos.x, textPos.y);
```

with

```
// apparently a space is added at the end of every entry in array line
if (lines[i] !== '\u200B ') context.fillText(lines[i], textPos.x, textPos.y);
```

Here's the above and then some more examples with more consecutive newlines.
![output_wuaehs](https://user-images.githubusercontent.com/5291713/28488002-52673532-6e55-11e7-8a9c-a9907544046e.gif)


You can check out the PR, however I'm not sure if anything goes horribly wrong somehow! In the test, I changed the last line from `CanvasTextWrapper(canvas, 'What an awesome library!', opts);` to  `CanvasTextWrapper(canvas, 'What an awesome\n\n\n library!', opts);` it worked as intended too.
![beefytest](https://user-images.githubusercontent.com/5291713/28488331-19884f2e-6e5c-11e7-9350-4902f096e3e7.png)
