### ISSUE TITLE
'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. 

### ISSUE THREAD

**Issue by peturh** [namniak/canvas-text-wrapper#22]
I'm getting this error from Chrome on my phone (Samsung Galaxy S5 mini (SM-G800F) Android 5.1.1)

`'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.`

Using Chrome version 50.0.2661.89 (Official build) (32-bit)

**Comment by namniak** [comment]
Is it breaking on your device? Looks like a warning, not error. Desktop chrome is ok.

**Comment by SamHH** [comment]
I'm getting this warning too. Think it needs attention.

```
'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated and will be removed in M55, around November 2016. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead. See https://www.chromestatus.com/features/5639849247768576 for more details.
```

**Comment by namniak** [comment]
`webkitImageSmoothingEnabled` is not being used anywhere in the code. I'm iterating through the context props and copying them here https://github.com/namniak/canvas-text-wrapper/blob/master/canvas-text-wrapper.js#L41 for later restoring after scale. So to speak, it's one of those props that context has in the browser. I assume when it's replaced with `imageSmoothingEnabled` it will be copied as it is just fine. As mentioned, I don't copy this prop explicitly. @SamHH  @peturh
